# Environment Settings
seed: 2020
reproducibility: True
data_path: ../data/
checkpoint_dir: 'saved/'
show_progress: True
log_wandb: True
wandb_project: 'general_recommendation'

# Data Settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

rm_dup_inter: False
user_inter_num_interval: "[0, inf)"
item_inter_num_interval: "[0, inf)"

# Training Settings_basic
epochs: 1000
train_batch_size: 64
learner: 'adam'
learning_rate: 0.001
eval_step: 1
stopping_step: 5
loss_decimal_place: 4
weight_decay: 0.000

# Model settings



#Evaluation Settings
eval_args:
    split: {'RS':[0.8, 0.1, 0.1]}
    group_by: user
    order: RO
    mode: full
repeatable: False
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 10
valid_metric: Recall@10
eval_batch_size: 4096
metric_decimal_place: 4

load_col: {"inter": ["user_id", "item_id", "rating", "timestamp"]}